const log=d=>document.getElementById('log').innerHTML+=`<div class="log-entry">${new Date().toLocaleTimeString('ru')}: ${d}</div>`,
eventsDiv=document.getElementById('events'),text1=document.getElementById('text1'),text2=document.getElementById('text2'),
swapDir=document.getElementById('swapDir'),logDiv=document.getElementById('log');let count=0,isPressed=false;
eventsDiv.addEventListener('click',()=>{log('click');eventsDiv.style.background='#333'}),
eventsDiv.addEventListener('mousedown',()=>{isPressed=true;log('mousedown');eventsDiv.style.background='#555'}),
eventsDiv.addEventListener('mousemove',()=>{isPressed&&log('mousemove')}),
eventsDiv.addEventListener('mouseleave',()=>{isPressed=false;log('mouseleave');eventsDiv.style.background='#151515'}),
eventsDiv.addEventListener('mouseup',()=>{isPressed=false;log('mouseup');eventsDiv.style.background='#333'}),
text1.addEventListener('focus',()=>{log('focus на текст1');text1.style.borderColor='#666'}),
text1.addEventListener('blur',()=>{log('blur из текст1');text1.style.borderColor='#444';swapDir.checked?!text1.value||text2.value||(text2.value=text1.value):text2.value=text1.value}),
text2.addEventListener('focus',()=>{log('focus на текст2');text2.style.borderColor='#666'}),
text2.addEventListener('blur',()=>{log('blur из текст2');text2.style.borderColor='#444';swapDir.checked&&text1.value===''&&(text1.value=text2.value)}),
document.getElementById('btnBold').addEventListener('click',()=>{const s=text1.value;text1.value='';text1.innerHTML=`<b>${s}</b>`;log('bold применен')}),
document.getElementById('btnItalic').addEventListener('click',()=>{const s=text1.value;text1.value='';text1.innerHTML=`<i>${s}</i>`;log('italic применен')}),
document.getElementById('btnUnderline').addEventListener('click',()=>{const s=text1.value;text1.value='';text1.innerHTML=`<u>${s}</u>`;log('underline применен')}),
document.getElementById('btnAdd').addEventListener('click',()=>{const el=document.createElement('div');el.className='dynamic-element';el.textContent=`Элемент ${++count}`;document.getElementById('dynamicContainer').appendChild(el);log(`добавлен элемент ${count}`)}),
document.getElementById('btnClear').addEventListener('click',()=>{document.getElementById('dynamicContainer').innerHTML='';count=0;log('элементы очищены')}),
swapDir.addEventListener('change',()=>{log(swapDir.checked?'режим: текст2→текст1':'режим: текст1→текст2')}),
logDiv.addEventListener('click',()=>{logDiv.innerHTML='';log('лог очищен')});
